language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 5.0
script:
- dotnet restore
- dotnet test --collect:"XPlat Code Coverage"
after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: u80MiP60pWcs+Ml4U1bfkAQzO+ApLiKRHZmV5FpnW0/NLirJsK05HlYWaKpHpW0Gc8AwDdsQG91s/zRUqJH90ykBFm3urEQ0UnOdB4Aua8kisgL2gT8EV8OvxiXqu0ExyTsEYKMpJzBn4b+yE+ncEgfrwyeYSFLmRO9SR0Q6TLOONkJDHSyppJSQHXrOVPr7RGuWLNQy3DcmdLnnywfssjRsF7i1njMMvVjigyoU1HKDWgTV5F9pAA0C/4utFbfRjV1/HT07bhfU/3llfzeQpFEfgev4k9HGY2OLlcACdv/TtkPajbgQgqhahN8xbPTb0UuFUcaOm98s0m1nL+xEdGkTw2jLwj6DzMVM/czvgb7sZSJq99s5KYn1GcCJpJPyyHJG+0OOzJ7T7PKXxgsCVy+Og5wgvaVo237F1HWriUIWAZE5lnLJbSzq93uTjc63OP3P87Kfx1MVa+j46Tjh76lgH8g2ayG4LDyyU81k468Kr7EdzOSauYbrojWiQumxjqd4E+alIQrZVEJ8OIW2/wl77Yo9PecYRo0JNX3QQr44EWdFhwpg5xep6iKPtU8D+ICzImXMVMgrKiSL3Asnbg6PcIVYBmui1dYk1QqUScOki6jzjYq2G2fYgmKZO05ilw9cf0Dm9zziINTzOnFJwnAnQRYMNYuHfF4ME+dDR/8=
