language: csharp
mono: none
sudo: required
dist: focal
dotnet: 7.0
script:
- dotnet restore
- dotnet test --filter 'TestCategory !~ Issues' --collect:"XPlat Code Coverage"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: bwOamiuG8vjh6fnbyd6b4goHLw5RtCuSaq+zboKt7qYu+htyjrRHBanoiIgxfpSXVlZ16PKkm47E5E56gC5e0msoT1dIX5EPCiS1mjsYRFGeNMjWLp1ikM/bJkLkm1nwMJfjm7iziHAWQMq51t/J5lJ13hGEI6Pe2YHWRnoCVwqYYbURDxMMl1aRC5s2GfvEpSAZRTbQZjUdEM1zsVwIBdI5GNbyxyd0NIEbDs7nnStb5g38RPdm4phUO1LY3SJBwGHPreIdPYjCEsMr7U6BA0OXMbUikHmPq8/fWNuDQgjgcfOe1+AKLLBWUs3xp11jkj0SRWUY44yPfymAungjFA+HXnUC/RjkWD82fOhYWRaNFqjmHPnIkdEbf6WmOD+o/o8iOd5lU19jug5WCRG/1aVhF3j9IT0OsYi8HdjEWGvwkhlLCvKRz9tkuc9zQiqLWg/ySneL1RseMzUzwvTLI3hP2FtaAIYGGYP2Gg7j3wRaef3UHYzfEU0PqI8MBupxKV3prozbpArGn9lL+IT//u1nM05b06DSluxc181laZoTJkz1gYvVJj9oIWgisfWsKQBPJJ66NdUVTd5Hn954tiy5tuFjwpLGnZcPxQtZvfWKEcanJLZGMJrDnKWfXNrSv9JR5GelvEQ922mVkqfScMYXE7zXg/OdaKMYzgAv4Ig=
