using Cecilifier.ApiDriver.MonoCecil;
using Cecilifier.Core.AST;
using Cecilifier.Core.Tests.Framework;
using NUnit.Framework;

namespace Cecilifier.Core.Tests.Integration;

[TestFixture(typeof(MonoCecilContext))]
public class InlineArraysTests<TResource> : ResourceTestBase<TResource> where TResource : IVisitorContext
{
    [Test]
    public void TestInlineArrays()
    {
        AssertResourceTestWithExplicitExpectation("Misc/InlineArrays", "System.Void InlineArrayTests::Test()");
    }
    
    [Test]
    public void TestInlineArraysRanges()
    {
        var options = new CecilifyTestOptions()
        {
            ResourceName = "Misc/InlineArraysRanges",
            IgnoredILErrors = "ReturnPtrToStack" // Sounds like a bug in ilverify (this is reproducible with code generated by c# compiler)
        };
        
        AssertResourceTestWithExplicitExpectation(options, "System.Void InlineArrayRangeTests::Test(System.Int32)");
    }
}
